### ISSUE TITLE
Add timestamp(int) to the spec

### ISSUE THREAD

**Issue by jsannemo** [google/cel-spec#224] opened 2022-01-30 18:14 UTC
cel-go and the compliance tests support timestamp(int) for creating timestamps from Unix timestamps in seconds. This should be added to the spec.

**Comment by TristonianJones** [comment] 2022-03-25 04:39
Thanks for filing. This is a duplicate of #122. I intend to update the spec function table docs in the coming quarter and will make sure to include this function then.

**Closed by TristonianJones** 2022-03-25 04:39 UTC
